#!/usr/bin/env fish

if not test -d ./archives
    mkdir ./archives
end

if not count ./archives/*.java >/dev/null
    set id 1
else
    set last_id (ls ./archives/*.java | sed -E 's|.*/([0-9]{4}).*|\1|' | sort -n | tail -n1)
    set id (math $last_id + 1)
end

set id (printf "%04d" $id)

echo "ID: $id"

read -P "Description: " description

set file "./archives/$(test -n "$description"; and printf "%s_%s.java" $id $description; or echo $id.java)"

set tempfile (mktemp)
echo "Problem: (editing in \$EDITOR...)"
$EDITOR $tempfile
for line in (cat $tempfile)
    if test -z "$line"
        echo // >>$file
        continue
    end
    echo "// $line" >>$file
end
rm -f $tempfile

echo >>$file
echo "// Sample Input" >>$file
for line in (cat ./src/in.txt)
    echo "// $line" >>$file
end

echo >>$file
echo "// Sample Output" >>$file
for line in (cat ./src/out.txt)
    echo "// $line" >>$file
end

echo >>$file
for line in (cat ./src/Main.java)
    echo $line >>$file
end
